FROM ubuntu:24.04
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
RUN apt-get update
RUN apt-get install -y --no-install-recommends swi-prolog-nox
RUN rm -rf /var/lib/apt/lists/*
WORKDIR /queryengine
COPY utils.pl utils.pl
COPY api.pl api.pl
COPY template.pl template.pl
COPY templates templates
COPY predicates predicates
COPY queryengine.elf.x64 .
RUN chmod +x queryengine.elf.x64
CMD ["./queryengine.elf.x64"]